-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.academic_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  name text NOT NULL,
  order_num integer DEFAULT 1,
  start_date date,
  end_date date,
  exam_start_date date,
  exam_end_date date,
  status text DEFAULT 'upcoming'::text CHECK (status = ANY (ARRAY['upcoming'::text, 'active'::text, 'exam'::text, 'grading'::text, 'closed'::text])),
  weight_pct integer DEFAULT 33,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT academic_periods_pkey PRIMARY KEY (id),
  CONSTRAINT academic_periods_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT academic_periods_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id)
);
CREATE TABLE public.academic_subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  name text NOT NULL,
  code text,
  color text DEFAULT '#4f6ef7'::text,
  coefficient numeric DEFAULT 1.0,
  credit_hours integer DEFAULT 3,
  category text DEFAULT 'general'::text CHECK (category = ANY (ARRAY['general'::text, 'specialized'::text, 'language'::text, 'science'::text, 'elective'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT academic_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT academic_subjects_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.academic_years (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  name text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_current boolean DEFAULT false,
  status text DEFAULT 'upcoming'::text CHECK (status = ANY (ARRAY['upcoming'::text, 'active'::text, 'completed'::text, 'archived'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT academic_years_pkey PRIMARY KEY (id),
  CONSTRAINT academic_years_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  course_id uuid NOT NULL,
  instructor_id uuid NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT announcements_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.annual_student_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  student_id uuid NOT NULL,
  class_section_id uuid,
  general_average numeric,
  gpa numeric,
  total_credits integer DEFAULT 0,
  rank_in_class integer,
  total_in_class integer,
  decision text DEFAULT 'pending'::text CHECK (decision = ANY (ARRAY['pending'::text, 'promoted'::text, 'repeating'::text, 'graduated'::text, 'honors'::text, 'conditional'::text])),
  honors text,
  published_at timestamp with time zone,
  teacher_comment text,
  CONSTRAINT annual_student_results_pkey PRIMARY KEY (id),
  CONSTRAINT annual_student_results_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT annual_student_results_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id),
  CONSTRAINT annual_student_results_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT annual_student_results_class_section_id_fkey FOREIGN KEY (class_section_id) REFERENCES public.class_sections(id)
);
CREATE TABLE public.annual_subject_averages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  student_id uuid NOT NULL,
  subject_id uuid NOT NULL,
  class_section_id uuid,
  period1_avg numeric,
  period2_avg numeric,
  period3_avg numeric,
  annual_average numeric,
  credit_hours integer DEFAULT 0,
  is_passing boolean,
  must_repeat boolean DEFAULT false,
  published_at timestamp with time zone,
  CONSTRAINT annual_subject_averages_pkey PRIMARY KEY (id),
  CONSTRAINT annual_subject_averages_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT annual_subject_averages_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id),
  CONSTRAINT annual_subject_averages_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT annual_subject_averages_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.academic_subjects(id),
  CONSTRAINT annual_subject_averages_class_section_id_fkey FOREIGN KEY (class_section_id) REFERENCES public.class_sections(id)
);
CREATE TABLE public.assignment_submissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  assignment_id uuid NOT NULL,
  student_id uuid NOT NULL,
  content_text text,
  file_url text,
  file_name text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'graded'::text, 'returned'::text, 'revision_requested'::text])),
  grade numeric,
  feedback text,
  submitted_at timestamp with time zone,
  graded_at timestamp with time zone,
  graded_by uuid,
  is_late boolean DEFAULT false,
  institution_id uuid,
  files jsonb DEFAULT '[]'::jsonb,
  score numeric,
  score_override boolean DEFAULT false,
  CONSTRAINT assignment_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT assignment_submissions_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT assignment_submissions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT assignment_submissions_graded_by_fkey FOREIGN KEY (graded_by) REFERENCES public.profiles(id),
  CONSTRAINT assignment_submissions_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lesson_id uuid NOT NULL,
  course_id uuid NOT NULL,
  title text NOT NULL,
  instructions text NOT NULL,
  submission_type text DEFAULT 'text'::text,
  opens_at timestamp with time zone,
  due_at timestamp with time zone,
  closes_at timestamp with time zone,
  time_limit_min integer,
  max_file_size_mb integer DEFAULT 10,
  allowed_types ARRAY DEFAULT ARRAY['pdf'::text, 'doc'::text, 'docx'::text, 'txt'::text, 'jpg'::text, 'png'::text, 'zip'::text],
  max_grade numeric DEFAULT 100,
  created_at timestamp with time zone DEFAULT now(),
  institution_id uuid,
  period_subject_id uuid,
  assignment_type text DEFAULT 'homework'::text,
  max_score numeric DEFAULT 20,
  weight numeric DEFAULT 1.0,
  allow_late boolean DEFAULT false,
  late_penalty_pct integer DEFAULT 20,
  resources jsonb DEFAULT '[]'::jsonb,
  rubric jsonb DEFAULT '[]'::jsonb,
  visible_from timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT assignments_pkey PRIMARY KEY (id),
  CONSTRAINT assignments_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT assignments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT assignments_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT assignments_period_subject_id_fkey FOREIGN KEY (period_subject_id) REFERENCES public.period_subjects(id),
  CONSTRAINT assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  admin_id uuid,
  action text NOT NULL,
  entity text NOT NULL,
  entity_id uuid,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.badges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  icon text NOT NULL,
  color text DEFAULT '#0891b2'::text,
  xp_reward integer DEFAULT 0,
  condition text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT badges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bulletins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  student_id uuid NOT NULL,
  academic_year_id uuid,
  academic_period_id uuid,
  bulletin_type text DEFAULT 'period'::text CHECK (bulletin_type = ANY (ARRAY['period'::text, 'annual'::text, 'final'::text])),
  pdf_url text,
  generated_at timestamp with time zone DEFAULT now(),
  published_at timestamp with time zone,
  CONSTRAINT bulletins_pkey PRIMARY KEY (id),
  CONSTRAINT bulletins_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT bulletins_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT bulletins_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id),
  CONSTRAINT bulletins_academic_period_id_fkey FOREIGN KEY (academic_period_id) REFERENCES public.academic_periods(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  icon text DEFAULT 'BookOpen'::text,
  color text DEFAULT '#4f6ef7'::text,
  parent_id uuid,
  order_num integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.certificates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  course_id uuid NOT NULL,
  enrollment_id uuid,
  certificate_number text NOT NULL UNIQUE,
  issued_at timestamp with time zone DEFAULT now(),
  pdf_url text,
  verify_url text NOT NULL,
  status text DEFAULT 'issued'::text CHECK (status = ANY (ARRAY['pending'::text, 'issued'::text])),
  CONSTRAINT certificates_pkey PRIMARY KEY (id),
  CONSTRAINT certificates_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT certificates_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT certificates_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id)
);
CREATE TABLE public.class_levels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  name text NOT NULL,
  order_num integer DEFAULT 1,
  level_type text DEFAULT 'secondary'::text CHECK (level_type = ANY (ARRAY['primary'::text, 'secondary'::text, 'university'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_levels_pkey PRIMARY KEY (id),
  CONSTRAINT class_levels_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT class_levels_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id)
);
CREATE TABLE public.class_schedule (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  period_subject_id uuid NOT NULL,
  class_section_id uuid,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  location_type text DEFAULT 'classroom'::text CHECK (location_type = ANY (ARRAY['classroom'::text, 'online'::text, 'hybrid'::text, 'lab'::text, 'field'::text])),
  room text,
  online_link text,
  override_date date,
  is_cancelled boolean DEFAULT false,
  cancellation_note text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_schedule_pkey PRIMARY KEY (id),
  CONSTRAINT class_schedule_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT class_schedule_period_subject_id_fkey FOREIGN KEY (period_subject_id) REFERENCES public.period_subjects(id),
  CONSTRAINT class_schedule_class_section_id_fkey FOREIGN KEY (class_section_id) REFERENCES public.class_sections(id)
);
CREATE TABLE public.class_sections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  class_level_id uuid NOT NULL,
  name text NOT NULL,
  capacity integer DEFAULT 30,
  main_teacher_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_sections_pkey PRIMARY KEY (id),
  CONSTRAINT class_sections_class_level_id_fkey FOREIGN KEY (class_level_id) REFERENCES public.class_levels(id),
  CONSTRAINT class_sections_main_teacher_id_fkey FOREIGN KEY (main_teacher_id) REFERENCES public.profiles(id),
  CONSTRAINT class_sections_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.cohort_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cohort_id uuid NOT NULL,
  student_id uuid NOT NULL,
  institution_id uuid NOT NULL,
  class_section_id uuid,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'repeating'::text, 'graduated'::text, 'withdrawn'::text, 'transferred'::text, 'suspended'::text])),
  student_code text,
  enrolled_at timestamp with time zone DEFAULT now(),
  graduated_at timestamp with time zone,
  gpa numeric,
  total_credits integer DEFAULT 0,
  notes text,
  CONSTRAINT cohort_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT cohort_enrollments_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES public.cohorts(id),
  CONSTRAINT cohort_enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT cohort_enrollments_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT cohort_enrollments_class_section_id_fkey FOREIGN KEY (class_section_id) REFERENCES public.class_sections(id)
);
CREATE TABLE public.cohorts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  program_id uuid,
  name text NOT NULL,
  code text,
  academic_year_id uuid,
  start_date date,
  expected_end_date date,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['forming'::text, 'active'::text, 'graduated'::text, 'suspended'::text, 'archived'::text])),
  max_capacity integer DEFAULT 40,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cohorts_pkey PRIMARY KEY (id),
  CONSTRAINT cohorts_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT cohorts_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT cohorts_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id)
);
CREATE TABLE public.continuous_assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  period_subject_id uuid NOT NULL,
  student_id uuid NOT NULL,
  assessment_type text DEFAULT 'devoir'::text CHECK (assessment_type = ANY (ARRAY['devoir'::text, 'controle'::text, 'participation'::text, 'projet'::text, 'tp'::text, 'oral'::text])),
  title text,
  score numeric,
  max_score numeric DEFAULT 20,
  weight numeric DEFAULT 1.0,
  graded_at date,
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT continuous_assessments_pkey PRIMARY KEY (id),
  CONSTRAINT continuous_assessments_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT continuous_assessments_period_subject_id_fkey FOREIGN KEY (period_subject_id) REFERENCES public.period_subjects(id),
  CONSTRAINT continuous_assessments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percent'::text, 'fixed'::text])),
  discount_value numeric NOT NULL,
  max_uses integer,
  used_count integer DEFAULT 0,
  course_id uuid,
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coupons_pkey PRIMARY KEY (id),
  CONSTRAINT coupons_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  instructor_id uuid NOT NULL,
  category_id uuid,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  subtitle text,
  description text NOT NULL DEFAULT ''::text,
  language text DEFAULT 'fr'::text CHECK (language = ANY (ARRAY['fr'::text, 'ht'::text, 'en'::text])),
  level text DEFAULT 'debutant'::text CHECK (level = ANY (ARRAY['debutant'::text, 'intermediaire'::text, 'avance'::text])),
  thumbnail_url text,
  preview_video_url text,
  preview_video_source text CHECK (preview_video_source = ANY (ARRAY['mux'::text, 'youtube'::text, 'vimeo'::text, 'url'::text])),
  pricing_model text DEFAULT 'free'::text CHECK (pricing_model = ANY (ARRAY['free'::text, 'paid'::text, 'certificate_only'::text])),
  price numeric,
  price_htg numeric,
  certificate_price numeric,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'review'::text, 'published'::text, 'archived'::text])),
  is_featured boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  requirements ARRAY DEFAULT '{}'::text[],
  what_you_learn ARRAY DEFAULT '{}'::text[],
  total_modules integer DEFAULT 0,
  total_lessons integer DEFAULT 0,
  total_duration_min integer DEFAULT 0,
  enrolled_count integer DEFAULT 0,
  rating_avg numeric DEFAULT 0,
  rating_count integer DEFAULT 0,
  search_vector tsvector,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  admin_feedback text,
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.profiles(id),
  CONSTRAINT courses_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  email text NOT NULL,
  type text NOT NULL,
  subject text NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_logs_pkey PRIMARY KEY (id),
  CONSTRAINT email_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.enrollments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  course_id uuid NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'refunded'::text])),
  payment_id text,
  progress_pct integer DEFAULT 0 CHECK (progress_pct >= 0 AND progress_pct <= 100),
  last_lesson_id uuid,
  enrolled_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT enrollments_last_lesson_id_fkey FOREIGN KEY (last_lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.faculties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  name text NOT NULL,
  code text,
  description text,
  dean_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT faculties_pkey PRIMARY KEY (id),
  CONSTRAINT faculties_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT faculties_dean_id_fkey FOREIGN KEY (dean_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.forum_replies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  thread_id uuid NOT NULL,
  author_id uuid NOT NULL,
  body text NOT NULL,
  is_accepted boolean DEFAULT false,
  upvotes integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT forum_replies_pkey PRIMARY KEY (id),
  CONSTRAINT forum_replies_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.forum_threads(id),
  CONSTRAINT forum_replies_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.forum_threads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  course_id uuid NOT NULL,
  lesson_id uuid,
  author_id uuid NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  is_question boolean DEFAULT true,
  is_pinned boolean DEFAULT false,
  is_answered boolean DEFAULT false,
  upvotes integer DEFAULT 0,
  reply_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT forum_threads_pkey PRIMARY KEY (id),
  CONSTRAINT forum_threads_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT forum_threads_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT forum_threads_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.institutional_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  student_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  class_section_id uuid NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'repeating'::text, 'graduated'::text, 'withdrawn'::text, 'transferred'::text])),
  enrolled_at timestamp with time zone DEFAULT now(),
  student_code text,
  cohort_id uuid,
  CONSTRAINT institutional_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT institutional_enrollments_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id),
  CONSTRAINT institutional_enrollments_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT institutional_enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT institutional_enrollments_class_section_id_fkey FOREIGN KEY (class_section_id) REFERENCES public.class_sections(id),
  CONSTRAINT institutional_enrollments_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES public.cohorts(id)
);
CREATE TABLE public.lesson_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  course_id uuid NOT NULL,
  content text NOT NULL,
  timestamp_sec integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lesson_notes_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_notes_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT lesson_notes_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT lesson_notes_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.lesson_progress (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  course_id uuid NOT NULL,
  is_completed boolean DEFAULT false,
  watch_time_sec integer DEFAULT 0,
  completed_at timestamp with time zone,
  last_watched_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lesson_progress_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_progress_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT lesson_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT lesson_progress_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.lesson_qa (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lesson_id uuid NOT NULL,
  course_id uuid NOT NULL,
  student_id uuid NOT NULL,
  question text NOT NULL,
  answer text,
  answered_by uuid,
  answered_at timestamp with time zone,
  upvotes integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lesson_qa_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_qa_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT lesson_qa_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT lesson_qa_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT lesson_qa_answered_by_fkey FOREIGN KEY (answered_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.lessons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  module_id uuid NOT NULL,
  course_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  order_num integer NOT NULL,
  duration_min integer,
  content_type text DEFAULT 'video'::text CHECK (content_type = ANY (ARRAY['video'::text, 'text'::text, 'quiz'::text, 'assignment'::text, 'resource'::text])),
  video_source text CHECK (video_source = ANY (ARRAY['mux'::text, 'youtube'::text, 'vimeo'::text, 'url'::text])),
  video_url text,
  mux_asset_id text,
  mux_playback_id text,
  mux_upload_id text,
  content_body text,
  resources jsonb DEFAULT '[]'::jsonb,
  is_free_preview boolean DEFAULT false,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  opens_at timestamp with time zone,
  closes_at timestamp with time zone,
  due_at timestamp with time zone,
  time_limit_min integer,
  max_attempts integer DEFAULT 1,
  grading_method text DEFAULT 'highest'::text,
  shuffle_questions boolean DEFAULT false,
  show_answers_after boolean DEFAULT true,
  password text,
  quiz_passing_score integer DEFAULT 70,
  CONSTRAINT lessons_pkey PRIMARY KEY (id),
  CONSTRAINT lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.modules(id),
  CONSTRAINT lessons_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.modules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  course_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  order_num integer NOT NULL,
  total_lessons integer DEFAULT 0,
  total_duration_min integer DEFAULT 0,
  is_free_preview boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT modules_pkey PRIMARY KEY (id),
  CONSTRAINT modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  course_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  content text NOT NULL,
  timestamp_sec integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notes_pkey PRIMARY KEY (id),
  CONSTRAINT notes_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT notes_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT notes_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  course_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text CHECK (currency = ANY (ARRAY['USD'::text, 'HTG'::text])),
  provider text NOT NULL CHECK (provider = ANY (ARRAY['stripe'::text, 'moncash'::text, 'paypal'::text])),
  provider_payment_id text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  receipt_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT payments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.period_exams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  period_subject_id uuid NOT NULL,
  student_id uuid NOT NULL,
  score numeric,
  max_score numeric DEFAULT 20,
  is_absent boolean DEFAULT false,
  comment text,
  graded_at date,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT period_exams_pkey PRIMARY KEY (id),
  CONSTRAINT period_exams_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT period_exams_period_subject_id_fkey FOREIGN KEY (period_subject_id) REFERENCES public.period_subjects(id),
  CONSTRAINT period_exams_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.period_grades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  period_subject_id uuid NOT NULL,
  student_id uuid NOT NULL,
  continuous_avg numeric,
  exam_score numeric,
  period_average numeric,
  letter_grade text,
  is_passing boolean,
  rank_in_class integer,
  teacher_comment text,
  calculated_at timestamp with time zone DEFAULT now(),
  published_at timestamp with time zone,
  CONSTRAINT period_grades_pkey PRIMARY KEY (id),
  CONSTRAINT period_grades_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT period_grades_period_subject_id_fkey FOREIGN KEY (period_subject_id) REFERENCES public.period_subjects(id),
  CONSTRAINT period_grades_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.period_subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  academic_period_id uuid NOT NULL,
  class_section_id uuid NOT NULL,
  subject_id uuid NOT NULL,
  teacher_id uuid,
  course_id uuid,
  continuous_weight_pct integer DEFAULT 60,
  exam_weight_pct integer DEFAULT 40,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT period_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT period_subjects_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT period_subjects_academic_period_id_fkey FOREIGN KEY (academic_period_id) REFERENCES public.academic_periods(id),
  CONSTRAINT period_subjects_class_section_id_fkey FOREIGN KEY (class_section_id) REFERENCES public.class_sections(id),
  CONSTRAINT period_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.academic_subjects(id),
  CONSTRAINT period_subjects_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id),
  CONSTRAINT period_subjects_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.platform_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  admin_signature_url text,
  admin_name text DEFAULT 'Direction EDHA'::text,
  CONSTRAINT platform_settings_pkey PRIMARY KEY (id),
  CONSTRAINT platform_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role text NOT NULL DEFAULT 'student'::text CHECK (role = ANY (ARRAY['student'::text, 'instructor'::text, 'institution'::text, 'admin'::text])),
  full_name text NOT NULL,
  email text,
  avatar_url text,
  bio text,
  website text,
  country text DEFAULT 'HT'::text,
  preferred_language text DEFAULT 'fr'::text CHECK (preferred_language = ANY (ARRAY['fr'::text, 'ht'::text, 'en'::text])),
  institution_name text,
  institution_verified boolean DEFAULT false,
  instructor_approved_at timestamp with time zone,
  total_courses_taught integer DEFAULT 0,
  total_students_taught integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  instructor_application jsonb,
  xp_points integer DEFAULT 0,
  streak_days integer DEFAULT 0,
  last_active_at timestamp with time zone,
  total_hours numeric DEFAULT 0,
  signature_url text,
  institution_logo_url text,
  institution_type text,
  institution_description text,
  institution_slug text UNIQUE,
  institution_address text,
  institution_phone text,
  director_name text,
  registration_number text,
  academic_mode text DEFAULT 'course'::text CHECK (academic_mode = ANY (ARRAY['course'::text, 'school'::text, 'university'::text])),
  period_type text DEFAULT 'trimestre'::text CHECK (period_type = ANY (ARRAY['trimestre'::text, 'semestre'::text])),
  periods_per_year integer DEFAULT 3,
  grading_scale integer DEFAULT 20,
  passing_grade numeric DEFAULT 10.0,
  repeat_policy text DEFAULT 'level'::text CHECK (repeat_policy = ANY (ARRAY['level'::text, 'subject'::text])),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.program_certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  program_id uuid NOT NULL,
  enrollment_id uuid,
  certificate_number text NOT NULL UNIQUE,
  issued_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'issued'::text,
  CONSTRAINT program_certificates_pkey PRIMARY KEY (id),
  CONSTRAINT program_certificates_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT program_certificates_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT program_certificates_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.program_enrollments(id)
);
CREATE TABLE public.program_courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  course_id uuid NOT NULL,
  order_num integer NOT NULL DEFAULT 1,
  is_required boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT program_courses_pkey PRIMARY KEY (id),
  CONSTRAINT program_courses_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT program_courses_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.program_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  program_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'refunded'::text])),
  payment_id uuid,
  enrolled_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  progress_pct integer DEFAULT 0,
  CONSTRAINT program_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT program_enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT program_enrollments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT program_enrollments_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  subtitle text,
  description text NOT NULL DEFAULT ''::text,
  language text NOT NULL DEFAULT 'fr'::text CHECK (language = ANY (ARRAY['fr'::text, 'ht'::text, 'en'::text, 'es'::text])),
  level text NOT NULL DEFAULT 'debutant'::text CHECK (level = ANY (ARRAY['debutant'::text, 'intermediaire'::text, 'avance'::text])),
  thumbnail_url text,
  category_id uuid,
  pricing_model text NOT NULL DEFAULT 'free'::text CHECK (pricing_model = ANY (ARRAY['free'::text, 'paid'::text])),
  price numeric,
  price_htg numeric,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'review'::text, 'published'::text, 'archived'::text])),
  is_featured boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  what_you_learn ARRAY DEFAULT '{}'::text[],
  requirements ARRAY DEFAULT '{}'::text[],
  total_courses integer DEFAULT 0,
  total_duration_min integer DEFAULT 0,
  enrolled_count integer DEFAULT 0,
  certificate_title text,
  practice_tools jsonb DEFAULT '[]'::jsonb,
  admin_feedback text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  faculty_id uuid,
  CONSTRAINT programs_pkey PRIMARY KEY (id),
  CONSTRAINT programs_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT programs_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT programs_faculty_id_fkey FOREIGN KEY (faculty_id) REFERENCES public.faculties(id)
);
CREATE TABLE public.quiz_attempts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  score integer,
  passed boolean,
  submitted_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  time_spent_sec integer,
  attempt_num integer DEFAULT 1,
  is_late boolean DEFAULT false,
  CONSTRAINT quiz_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT quiz_attempts_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT quiz_attempts_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.quiz_questions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lesson_id uuid NOT NULL,
  question text NOT NULL,
  type text DEFAULT 'single'::text CHECK (type = ANY (ARRAY['single'::text, 'multiple'::text, 'true_false'::text, 'fill_blank'::text])),
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  explanation text,
  points integer DEFAULT 1,
  order_num integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quiz_questions_pkey PRIMARY KEY (id),
  CONSTRAINT quiz_questions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  course_id uuid NOT NULL,
  student_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  is_verified_purchase boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT reviews_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.subject_prerequisites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_id uuid NOT NULL,
  subject_id uuid NOT NULL,
  prerequisite_id uuid NOT NULL,
  min_grade numeric DEFAULT 10.0,
  CONSTRAINT subject_prerequisites_pkey PRIMARY KEY (id),
  CONSTRAINT subject_prerequisites_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.profiles(id),
  CONSTRAINT subject_prerequisites_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.academic_subjects(id),
  CONSTRAINT subject_prerequisites_prerequisite_id_fkey FOREIGN KEY (prerequisite_id) REFERENCES public.academic_subjects(id)
);
CREATE TABLE public.user_badges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  badge_id uuid NOT NULL,
  earned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_badges_pkey PRIMARY KEY (id),
  CONSTRAINT user_badges_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_badges_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES public.badges(id)
);
CREATE TABLE public.wishlist (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  course_id uuid NOT NULL,
  added_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT wishlist_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT wishlist_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);